### ISSUE TITLE
Support nightly in docker images

### ISSUE THREAD

**Issue by tmpfs** [napi-rs/package-template#277]
Hi,

Thanks for all the work on `napi-rs`!

I am trying to get a publish pipeline compiling using the `nightly` toolchain. For the builds that don't use docker this is pretty simple but I am not sure how I could update the `musl` builds that use docker to compile using the `nightly` toolchain. Any ideas?

Also, I noticed that for the `x86_64-unknown-linux-gnu` target building using docker seems to be redundant as it is using an `ubuntu-latest` image. See: https://github.com/napi-rs/package-template/blob/main/.github/workflows/CI.yaml#L40-L47

I switched it to just `yarn build` and it seems good or am i missing something here?

**Comment by Brooooooklyn** [comment]
There is no problem with `nightly` if you have `rust-toolchain` in your project: https://github.com/Brooooooklyn/canvas/blob/main/rust-toolchain . I think it's the recommend way to use `nightly rust`.

> I switched it to just yarn build and it seems good or am i missing something here?

If your package is running on the latest `linux-gnu` system, it won't be a problem.

But if your packages will run in old linux distribution, it could be `glibc` compatible problem.

The glibc version on `ubuntu-latest` is `2.31`, which means it may not compatible with the docker containers based `node:lts` image.

**Comment by tmpfs** [comment]
That was very helpful, thank you 🙏
