### ISSUE TITLE
Linker -- not found

### ISSUE THREAD

**Issue by xHyroM** [napi-rs/package-template#301]
I am currently getting this error on `stable - armv7-linux-androideabi - node@16 ` and `stable - stable - aarch64-linux-android - node@16 `. A few days ago it all worked, I didn't modify anything.
![image](https://user-images.githubusercontent.com/56601352/181023299-f7b5110f-85fd-498f-b742-ba455f7ec9dd.png)

CI file: https://github.com/xHyroM/bun-utilities/blob/master/.github/workflows/CI.yml

**Comment by Brooooooklyn** [comment]
ref: https://github.com/actions/virtual-environments/issues/5879
