### ISSUE TITLE
请问如何修改配置文件，来选择性的支持某些平台

### ISSUE THREAD

**Issue by i-user-link** [napi-rs/package-template#307]
如题，因为一些依赖库不跨平台，所以需要屏蔽某些平台。

是只需要修改 package.json 中 napi 下的 additional ，还是说 .github/workflows/CI.yml 也需要编辑？

有没有比较简单的配置办法？ 比如修改某个配置文件，然后运行cli，模板生成CI.yml什么的

**Comment by Brooooooklyn** [comment]
这种情况建议使用 `napi new` 命令来创建项目，创建过程中可以选择需要支持的平台
