### ISSUE TITLE
node16 no longer available in FreeBSD pipeline

### ISSUE THREAD

**Issue by traeok** [napi-rs/package-template#313]
Hello,

I'm currently working on a project that uses napi-rs, and noticed that the FreeBSD runner is no longer able to find node16 from the package manager. To verify this, I forked this template repo and tried running the pipelines on the fork. You can find the output here:

https://github.com/traeok/package-template/actions/runs/3661652187/jobs/6190049422

Aside from that, the other stages seem to be working as intended. Thanks for maintaining such an awesome library!

**Comment by Brooooooklyn** [comment]
Fixed in https://github.com/napi-rs/package-template/pull/312
