### ISSUE TITLE
Optional dependencies with Yarn issue

### ISSUE THREAD

**Issue by MatthD** [napi-rs/package-template#344]
I have a project which use the template, I am not able or don't want to build for FREEBSD,

But magically the `package.json` on npm contains `optionalDependencies`which contains the FreeBDS one.

With nom , no problem, but with yarn it will lead to an error not found and the main package will not be installed

You can try with `yarn install @avahq/resampler-native-rubato`

Side question but why does. it even try to download it ? Does this means that it will download all binaries in my project ? (I supposed It was more like `prebuild` which get the only binary needed)

**Comment by Brooooooklyn** [comment]
remove this dir https://github.com/AvaHQ/resampler-native-rubato/tree/main/npm/freebsd-x64
and this line https://github.com/AvaHQ/resampler-native-rubato/blob/main/package.json#L17
